### ISSUE TITLE
Failed to run it

### ISSUE THREAD

**Issue by Jackchengwang** [raghur/vue-testdrive#2]
Content root path: C:\learnings\spa\vue-testdrive-master
Now listening on: http://localhost:5000
Application started. Press Ctrl+C to shut down.
info: Microsoft.AspNetCore.NodeServices[0]
      ts-loader: Using typescript@2.7.1 and C:\learnings\spa\vue-testdrive-master\tsconfig.json
fail: Microsoft.AspNetCore.NodeServices[0]
      ?[1m?[31mERROR in ?[39m?[22m?[1m?[36mC:/learnings/spa/vue-testdrive-master/ClientApp/store/index.ts(9,9)?[39m?[22m?[1m?[31m:?[39m?[22m
fail: Microsoft.AspNetCore.NodeServices[0]

      ?[90mTS2345: ?[39mArgument of type 'typeof "C:/learnings/spa/vue-testdrive-master/node_modules/vuex/types/index"' is not assignable to parameter of type 'PluginObject<any> | PluginFunction<any>'.
        Type 'typeof "C:/learnings/spa/vue-testdrive-master/node_modules/vuex/types/index"' is not assignable to type 'PluginFunction<any>'.
          Type 'typeof "C:/learnings/spa/vue-testdrive-master/node_modules/vuex/types/index"' provides no match for the signature '(Vue: VueConstructor<Vue>, options?: any): void'.
fail: Microsoft.AspNetCore.NodeServices[0]
      ?[1m?[31mERROR in ?[39m?[22m?[1m?[36mC:/learnings/spa/vue-testdrive-master/node_modules/vue-class-component/lib/declarations.d.ts(6,33)?[39m?[22m?[1m?[31m:?[39m?[22m
fail: Microsoft.AspNetCore.NodeServices[0]

      ?[90mTS2702: ?[39m'Vue' only refers to a type, but is being used as a namespace here.
fail: Microsoft.AspNetCore.NodeServices[0]
      ?[1m?[31mERROR in ?[39m?[22m?[1m?[36mC:/learnings/spa/vue-testdrive-master/node_modules/vue-router/types/router.d.ts(4,35)?[39m?[22m?[1m?[31m:?[39m?[22m
fail: Microsoft.AspNetCore.NodeServices[0]

      ?[90mTS2709: ?[39mCannot use namespace 'Vue' as a type.
fail: Microsoft.AspNetCore.NodeServices[0]
      ?[1m?[31mERROR in ?[39m?[22m?[1m?[36mC:/learnings/spa/vue-testdrive-master/node_modules/vue-router/types/router.d.ts(13,43)?[39m?[22m?[1m?[31m:?[39m?[22m
fail: Microsoft.AspNetCore.NodeServices[0]

      ?[90mTS2709: ?[39mCannot use namespace 'Vue' as a type.
fail: Microsoft.AspNetCore.NodeServices[0]
      ?[1m?[31mERROR in ?[39m?[22m?[1m?[36mC:/learnings/spa/vue-testdrive-master/node_modules/vue-router/types/router.d.ts(19,8)?[39m?[22m?[1m?[31m:?[39m?[22m
fail: Microsoft.AspNetCore.NodeServices[0]

      ?[90mTS2709: ?[39mCannot use namespace 'Vue' as a type.
fail: Microsoft.AspNetCore.NodeServices[0]
      ?[1m?[31mERROR in ?[39m?[22m?[1m?[36mC:/learnings/spa/vue-testdrive-master/node_modules/vue-router/types/router.d.ts(93,25)?[39m?[22m?[1m?[31m:?[39m?[22m
fail: Microsoft.AspNetCore.NodeServices[0]

      ?[90mTS2709: ?[39mCannot use namespace 'Vue' as a type.
fail: Microsoft.AspNetCore.NodeServices[0]
      ?[1m?[31mERROR in ?[39m?[22m?[1m?[36mC:/learnings/spa/vue-testdrive-master/node_modules/vue-router/types/vue.d.ts(17,13)?[39m?[22m?[1m?[31m:?[39m?[22m
fail: Microsoft.AspNetCore.NodeServices[0]

      ?[90mTS2428: ?[39mAll declarations of 'ComponentOptions' must have identical type parameters.
fail: Microsoft.AspNetCore.NodeServices[0]
      ?[1m?[31mERROR in ?[39m?[22m?[1m?[36mC:/learnings/spa/vue-testdrive-master/node_modules/vue-router/types/vue.d.ts(17,40)?[39m?[22m?[1m?[31m:?[39m?[22m
fail: Microsoft.AspNetCore.NodeServices[0]

      ?[90mTS2709: ?[39mCannot use namespace 'Vue' as a type.
fail: Microsoft.AspNetCore.NodeServices[0]
      ?[1m?[31mERROR in ?[39m?[22m?[1m?[36mC:/learnings/spa/vue-testdrive-master/node_modules/vue/types/options.d.ts(53,18)?[39m?[22m?[1m?[31m:?[39m?[22m
fail: Microsoft.AspNetCore.NodeServices[0]

      ?[90mTS2428: ?[39mAll declarations of 'ComponentOptions' must have identical type parameters.
fail: Microsoft.AspNetCore.NodeServices[0]
      ?[1m?[31mERROR in ?[39m?[22m?[1m?[36mC:/learnings/spa/vue-testdrive-master/node_modules/vuex/types/vue.d.ts(9,13)?[39m?[22m?[1m?[31m:?[39m?[22m
fail: Microsoft.AspNetCore.NodeServices[0]

      ?[90mTS2428: ?[39mAll declarations of 'ComponentOptions' must have identical type parameters.
fail: Microsoft.AspNetCore.NodeServices[0]
      ?[1m?[31mERROR in ?[39m?[22m?[1m?[36mC:/learnings/spa/vue-testdrive-master/node_modules/vuex/types/vue.d.ts(9,40)?[39m?[22m?[1m?[31m:?[39m?[22m
fail: Microsoft.AspNetCore.NodeServices[0]

      ?[90mTS2709: ?[39mCannot use namespace 'Vue' as a type.
info: Microsoft.AspNetCore.NodeServices[0]
      Version: typescript ?[1m2.7.1?[22m
info: Microsoft.AspNetCore.NodeServices[0]
      Time: ?[1m4042?[22mms
info: Microsoft.AspNetCore.NodeServices[0]
      webpack built 0a3088ddfeadbd2e9069 in 11207ms
fail: Microsoft.AspNetCore.NodeServices[0]
      Hash: 0a3088ddfeadbd2e9069

**Comment by raghur** [comment]
@Jackchengwang - try now. I had to update dependencies - so nuke your node_modules, www/dist etc folders before trying. 

I've found that it fails if I use the latest version of [vue-loader 14.1.0](https://github.com/vuejs/vue-loader/releases/tag/v14.1.0) - if you can take a look at updating the dependency and making it work, I'd appreciate a PR :)
